### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by mbowcutt** [adp90/cwrubeta-services#4]
When I run the server, I get some sort of connection refused error:
```
❯ bin/rails server
=> Booting Puma
=> Rails 5.1.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: production
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2017-08-24 00:55:52 -0400

PG::ConnectionBad (could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
):

pg (0.21.0) lib/pg.rb:56:in `initialize'
pg (0.21.0) lib/pg.rb:56:in `new
```

Running the testbuild completes but encounters these errors:
 ```
❯ ./testbuild.sh
...
,,,
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "username"=>nil, "password"=>n
il, "database"=>"db/development"}
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

Tasks: TOP => db:create
(See full trace by running task with --trace)
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
```

When I open the site I get this:
![chrome_2017-08-24_00-32-05](https://user-images.githubusercontent.com/20796734/29650255-c8b1d3b0-8867-11e7-9e2b-793b19d029e2.png)

What mean what do?

**Comment by adp90** [comment]
This means that you don't have PostgreSQL installed. You should be able to fix this by running `brew install postgres` or the equivalent for your system.

Thanks, I'll make a note about this in the readme.

**Comment by adp90** [comment]
It turns out the problem is that you need to start the PostgreSQL server. Just ran into it myself.
